# Generated by Django 6.0.4 on 2026-08-21 09:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condition_order', models.CharField(choices=[('pairwise_first', 'Pairwise comparisons first'), ('ranking_first', 'Ranking lists first')], max_length=20)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('prolific_id', models.CharField(blank=True, max_length=100)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_code', models.CharField(blank=True, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='FinalResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_design', models.CharField(choices=[('pairwise', 'Pairwise'), ('ranking', 'Ranking')], max_length=10)),
                ('preferred_reason', models.TextField(blank=True)),
                ('pairwise_validation_accuracy', models.FloatField(blank=True, null=True)),
                ('ranking_validation_accuracy', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_response', to='project4.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.CharField(choices=[('pairwise', 'Pairwise'), ('ranking', 'Ranking')], max_length=10)),
                ('phase', models.CharField(choices=[('practice', 'Practice / attention check'), ('elicitation', 'Elicitation'), ('validation', 'Held-out validation')], max_length=15)),
                ('trial_index', models.IntegerField()),
                ('movie_ids', models.JSONField()),
                ('response', models.JSONField()),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='project4.participant')),
            ],
            options={
                'ordering': ['participant_id', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.CharField(choices=[('pairwise', 'Pairwise'), ('ranking', 'Ranking')], max_length=10)),
                ('ease_of_use', models.IntegerField()),
                ('cognitive_load', models.IntegerField()),
                ('enjoyment', models.IntegerField()),
                ('trust', models.IntegerField()),
                ('free_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='project4.participant')),
            ],
            options={
                'unique_together': {('participant', 'design')},
            },
        ),
    ]
