# Generated by Django 6.0.4 on 2026-08-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='age_bracket',
            field=models.CharField(blank=True, choices=[('18-24', '18-24'), ('25-34', '25-34'), ('35-44', '35-44'), ('45-54', '45-54'), ('55+', '55+'), ('na', 'Prefer not to say')], max_length=10),
        ),
        migrations.AddField(
            model_name='participant',
            name='movie_frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'A few times a week'), ('monthly', 'A few times a month'), ('rarely', 'Rarely')], max_length=10),
        ),
        migrations.AddField(
            model_name='participant',
            name='recsys_familiarity',
            field=models.CharField(blank=True, choices=[('none', 'Never used one'), ('some', 'Used one occasionally'), ('regular', 'Use one regularly (e.g. Netflix/IMDb recommendations)')], max_length=10),
        ),
        migrations.AddField(
            model_name='trial',
            name='is_correct',
            field=models.BooleanField(blank=True, help_text="Only meaningful for phase='practice': did the response match the instructed target? Used as the pre-registered attention-check exclusion criterion (report, section 3.5).", null=True),
        ),
    ]
